#!/usr/bin/env bash
# Syntax-check nginx/epistemic-ontology.net.conf without touching a server.
#
# The config cannot be fed to `nginx -t` directly: it is a conf.d fragment with
# no events{}/http{} of its own, it names TLS certificates under
# /etc/letsencrypt that exist only on the deployed host, and it listens on
# privileged ports. This builds a throwaway harness that supplies those three
# things and runs the real nginx parser over the file.
#
# The harness reproduces the one structural fact the config depends on: the
# main nginx.conf includes conf.d/*.conf from INSIDE its http{} block, which is
# what makes http-context directives legal in this file -- the `map` blocks and
# `types_hash_max_size`. Get that wrong and the file is rejected at deploy.
#
# WHAT THIS PROVES
#   The file parses, and every directive is valid in the context it appears in.
#   Without this, that class of error surfaced only at deploy time, when
#   server/install.sh runs `nginx -t` on production (it tests before it keeps,
#   and rolls back, so it was never dangerous -- just a slow way to find out).
#
# WHAT IT DOES NOT PROVE
#   Runtime behaviour. Nothing is served and no request is made. In particular
#   it will not reproduce the server's `could not build optimal types_hash`
#   warning: that depends on the host's mime.types (1002 entries on the
#   deployed Amazon Linux box, 92 on a stock Ubuntu workstation) and on
#   key-length packing against types_hash_bucket_size, not on anything in this
#   repository. Confirm warnings with `nginx -t` on the server itself.
#
# Usage:
#     ./check-nginx.sh                 # check nginx/epistemic-ontology.net.conf
#     ./check-nginx.sh path/to.conf    # check another fragment
set -uo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
CONF="${1:-$HERE/nginx/epistemic-ontology.net.conf}"

if [ -t 1 ]; then G=$'\033[32m'; R=$'\033[31m'; Y=$'\033[33m'; Z=$'\033[0m'
else G=''; R=''; Y=''; Z=''; fi

# nginx lives in sbin, which is not on a normal user's PATH -- `command -v
# nginx` returns nothing on a machine that has it installed and running. Look
# in the usual places before concluding it is absent.
NGINX=""
for candidate in nginx /usr/sbin/nginx /usr/local/sbin/nginx /sbin/nginx \
                 /usr/local/nginx/sbin/nginx; do
  if command -v "$candidate" >/dev/null 2>&1; then NGINX="$candidate"; break; fi
  if [ -x "$candidate" ]; then NGINX="$candidate"; break; fi
done
[ -n "$NGINX" ] || {
  echo "error: no nginx binary found (looked on PATH and in the sbin dirs)." >&2
  echo "       install it to enable this check: sudo apt install nginx" >&2
  echo "       it is needed only as a parser -- nothing is served or started." >&2
  exit 2
}
command -v openssl >/dev/null || {
  echo "error: openssl not found; needed for the throwaway test certificate" >&2
  exit 2
}
[ -f "$CONF" ] || { echo "error: config not found: $CONF" >&2; exit 2; }

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
mkdir -p "$TMP/tmp" "$TMP/logs"

printf 'nginx    %s\n' "$($NGINX -v 2>&1 | sed 's/^nginx version: //')"
printf 'config   %s\n' "${CONF#"$HERE"/}"

# A certificate the config can actually open. Self-signed, one day, discarded
# with the temp directory -- `nginx -t` opens the files, it does not care who
# signed them.
openssl req -x509 -newkey rsa:2048 -keyout "$TMP/key.pem" -out "$TMP/cert.pem" \
  -days 1 -nodes -subj "/CN=epistemic-ontology.net" >/dev/null 2>&1 || {
  echo "error: could not generate the test certificate" >&2; exit 2; }

# Two substitutions, both only so the parse can run as an unprivileged user:
#   certificates -> the throwaway pair above
#   80/443 -> 8080/8443, because `nginx -t` opens the listen sockets, and a
#     non-root process cannot bind a privileged port. Only `listen` lines are
#     touched, so redirect targets and headers keep their real ports.
sed -e "s|/etc/letsencrypt/live/epistemic-ontology.net/fullchain.pem|$TMP/cert.pem|g" \
    -e "s|/etc/letsencrypt/live/epistemic-ontology.net/privkey.pem|$TMP/key.pem|g" \
    "$CONF" \
  | sed -E '/^[[:space:]]*listen/{s/\b80\b/8080/; s/\b443\b/8443/}' \
  > "$TMP/fragment.conf"

MIME=""
if [ -f /etc/nginx/mime.types ]; then
  MIME="    include /etc/nginx/mime.types;"
else
  printf '%s\n' "  ${Y}note${Z}  /etc/nginx/mime.types absent; types{} blocks parse but"
  printf '%s\n' "        inherited MIME mappings are not represented"
fi

cat > "$TMP/nginx.conf" <<EOF
# Generated by check-nginx.sh. The fragment is included from inside http{},
# exactly as conf.d/*.conf is on the server.
pid $TMP/nginx.pid;
error_log $TMP/logs/error.log;
events { worker_connections 64; }
http {
$MIME
    default_type application/octet-stream;
    access_log $TMP/logs/access.log;
    client_body_temp_path $TMP/tmp;
    proxy_temp_path $TMP/tmp;
    fastcgi_temp_path $TMP/tmp;
    uwsgi_temp_path $TMP/tmp;
    scgi_temp_path $TMP/tmp;
    include $TMP/fragment.conf;
}
EOF

out="$($NGINX -t -c "$TMP/nginx.conf" 2>&1)"
status=$?

# Report nginx's own words, with the harness path stripped so the output reads
# as being about the config rather than about a temp directory.
printf '%s\n' "$out" | sed "s|$TMP/nginx.conf|<harness>|g; s/^/  /"

warnings="$(printf '%s\n' "$out" | grep -c '\[warn\]')"
if [ "$status" -eq 0 ]; then
  if [ "$warnings" -gt 0 ]; then
    # nginx exits 0 on warnings. Surfaced, not fatal: a warning here is about
    # this workstation's nginx build, not about the committed config.
    printf '\n  %sok%s    config parses (%s warning(s) above, not fatal)\n' \
      "$G" "$Z" "$warnings"
  else
    printf '\n  %sok%s    config parses; every directive valid in context\n' "$G" "$Z"
  fi
  exit 0
fi

printf '\n  %sFAIL%s  nginx rejected the config (see above)\n' "$R" "$Z"
printf '        Note the two rewrites this harness makes (certificate paths,\n'
printf '        listen ports) -- an error mentioning those is the harness, not\n'
printf '        the committed file.\n'
exit 1
