#!/usr/bin/env bash
# Migrate the Record Harm Ontology from the placeholder example.org namespace to
# the permanent epistemic-ontology.net base, and stage the serializations into
# the website for hosting.
#
# This is the concrete replacement of the "dangling" example.org IRI:
#   http://example.org/record-harm-ontology#  ->  https://www.epistemic-ontology.net/record-harm#
#
# Re-runnable. Pass the source repo path as $1 (defaults to a sibling checkout).
set -euo pipefail

SRC="${1:-$HOME/claude/record-harm-ontology}"
DEST="$(cd "$(dirname "$0")" && pwd)/ontology-dist/record-harm"

OLD='http://example.org/record-harm-ontology#'
NEW='https://www.epistemic-ontology.net/record-harm#'

declare -A FILES=(
  ["ontology/record-harm-ontology.ttl"]="record-harm-ontology.ttl"
  ["shapes/record-harm-shapes.ttl"]="record-harm-shapes.ttl"
  ["examples/example-harm-events.ttl"]="example-harm-events.ttl"
)

if [ ! -d "$SRC" ]; then
  echo "error: source repo not found at $SRC (pass it as the first argument)" >&2
  exit 1
fi

mkdir -p "$DEST"
for src_rel in "${!FILES[@]}"; do
  src="$SRC/$src_rel"
  out="$DEST/${FILES[$src_rel]}"
  if [ ! -f "$src" ]; then
    echo "warn: missing $src — skipping" >&2
    continue
  fi
  # The namespace rewrite is textual, not IRI-aware, and deliberately so: the
  # placeholder also appears inside a typed string literal (the sh:namespace in
  # the shapes' sh:prefixes node), and an IRI-only rewrite would leave that
  # pointing at the old base, silently breaking the SPARQL-based constraints
  # that resolve prefixes through it.
  #
  # The flip side is that the rewrite also hits COMMENTS, and the ontology
  # header carries a TODO describing example.org as a placeholder to be
  # migrated away from. Rewritten verbatim, the hosted copy would assert that
  # its own permanent base "is an RFC 2606 placeholder -- non-resolvable and
  # unowned", which is false and sits in the document served as canonical. So
  # that block is replaced with a provenance note. cf. stage-record.sh, which
  # has the same hazard and handles it by matching the URL form only.
  sed "s|${OLD}|${NEW}|g" "$src" \
    | awk -v new="$NEW" '
        /^# TODO \[namespace\]:/ {
          print "# [hosted copy] Generated by migrate.sh in the website repository:"
          print "# this serialization was rewritten from the drafting placeholder"
          print "# namespace to the permanent base"
          print "#   " new
          print "# The source repository still carries the placeholder; adopting this base"
          print "# there is tracked as a v4.0 breaking change. Do not edit this file -- it"
          print "# is regenerated. The placeholder is deliberately not named here: the"
          print "# site build greps the hosted output for it to catch real leaks."
          skip = 1
          next
        }
        skip && /handle it on its own\.$/ { skip = 0; next }
        skip { next }
        { print }
      ' > "$out"
  echo "migrated  $src_rel  ->  site/record-harm/${FILES[$src_rel]}"
done

# Sanity: no example.org reference of any kind should remain in the hosted
# copies -- not even in a comment, since build.py --check greps the published
# output for the string and will fail the build if one survives.
if grep -rl "example.org" "$DEST" >/dev/null 2>&1; then
  echo "error: example.org still present in migrated output" >&2
  exit 1
fi
# And the rewritten TODO must not survive: it would claim the permanent base is
# a placeholder.
if grep -rl "RFC 2606 placeholder" "$DEST" >/dev/null 2>&1; then
  echo "error: the placeholder TODO survived into the hosted copy" >&2
  exit 1
fi
echo "done — hosted namespace is now ${NEW}"
