#!/usr/bin/env bash
# Migrate the Record Harm Ontology from the placeholder example.org namespace to
# the permanent epistemic-ontology.net base, and stage the serializations into
# the website for hosting.
#
# This is the concrete replacement of the "dangling" example.org IRI:
#   http://example.org/record-harm-ontology#  ->  https://www.epistemic-ontology.net/record-harm#
#
# Re-runnable. Pass the source repo path as $1 (defaults to a sibling checkout).
set -euo pipefail

SRC="${1:-$HOME/claude/record-harm-ontology}"
DEST="$(cd "$(dirname "$0")" && pwd)/ontology-dist/record-harm"

OLD='http://example.org/record-harm-ontology#'
NEW='https://www.epistemic-ontology.net/record-harm#'

declare -A FILES=(
  ["ontology/record-harm-ontology.ttl"]="record-harm-ontology.ttl"
  ["shapes/record-harm-shapes.ttl"]="record-harm-shapes.ttl"
  ["examples/example-harm-events.ttl"]="example-harm-events.ttl"
)

if [ ! -d "$SRC" ]; then
  echo "error: source repo not found at $SRC (pass it as the first argument)" >&2
  exit 1
fi

mkdir -p "$DEST"
for src_rel in "${!FILES[@]}"; do
  src="$SRC/$src_rel"
  out="$DEST/${FILES[$src_rel]}"
  if [ ! -f "$src" ]; then
    echo "warn: missing $src — skipping" >&2
    continue
  fi
  # The namespace rewrite is textual, not IRI-aware, and deliberately so: the
  # placeholder also appears inside a typed string literal (the sh:namespace in
  # the shapes' sh:prefixes node), and an IRI-only rewrite would leave that
  # pointing at the old base, silently breaking the SPARQL-based constraints
  # that resolve prefixes through it.
  #
  # The flip side is that the rewrite also hits COMMENTS, and the ontology
  # header carries a TODO describing example.org as a placeholder to be
  # migrated away from. Rewritten verbatim, the hosted copy would assert that
  # its own permanent base "is an RFC 2606 placeholder -- non-resolvable and
  # unowned", which is false and sits in the document served as canonical. So
  # that block is replaced with a provenance note. cf. stage-record.sh, which
  # has the same hazard and handles it by matching the URL form only.
  sed "s|${OLD}|${NEW}|g" "$src" \
    | awk -v new="$NEW" '
        /^# TODO \[namespace\]:/ {
          print "# [hosted copy] Generated by migrate.sh in the website repository:"
          print "# this serialization was rewritten from the drafting placeholder"
          print "# namespace to the permanent base"
          print "#   " new
          print "# The source repository still carries the placeholder; adopting this base"
          print "# there is tracked as a v4.0 breaking change. Do not edit this file -- it"
          print "# is regenerated. The placeholder is deliberately not named here: the"
          print "# site build greps the hosted output for it to catch real leaks."
          skip = 1
          next
        }
        skip && /handle it on its own\.$/ { skip = 0; next }
        skip { next }
        { print }
      ' > "$out"
  echo "migrated  $src_rel  ->  site/record-harm/${FILES[$src_rel]}"
done

# --- the documentation pages ------------------------------------------------
# Two of the three docs/ files belong on the website. They are GENERATED here
# rather than copied by hand for the same reason the serializations are: a hand
# copy is a fact that drifts, and this site has already shipped a licence that
# said MIT after the ontology went CC BY, a migration note that said v3.0 after
# v3.0 was spent, and a table of five prime harms after there were six.
#
# docs/QUERIES.md             -> /record-harm/queries/
#   Needs the namespace rewrite above all else: it carries 27 example.org IRIs,
#   one in every PREFIX line. Published verbatim, every copy-pasteable query on
#   the site would name a namespace absent from the data actually served.
# docs/ONTOLOGY-COMPARISON.md -> /record-harm/comparison/
#   Clean of placeholder IRIs; needs only its ../CHANGELOG.md link repointed at
#   GitHub, which would otherwise 404.
# docs/ARCHITECTURE.md        -> NOT published, deliberately.
#   Maintainer-facing release rationale (the v2.3 defect, the primality tests,
#   the breaking-change table) whose value depends on knowing this repository's
#   history. The record-harm page links to it on GitHub instead -- the same
#   choice content/ontologies/record.md already makes for ROOT.md.

PAGES="$(cd "$(dirname "$0")" && pwd)/content/pages"
GH_BLOB="https://github.com/commuted/record-harm-ontology/blob/main"

stage_doc() {  # stage_doc <src-rel> <out-file> <slug> <title> <description>
  local src="$SRC/$1" out="$PAGES/$2" slug="$3" title="$4" desc="$5"
  if [ ! -f "$src" ]; then
    echo "warn: missing $1 -- skipping" >&2
    return
  fi
  {
    echo "---"
    echo "# GENERATED by migrate.sh from $1 in the ontology repository."
    echo "# Do not edit here; edit it there and re-run 'make stage'."
    echo "# The namespace is rewritten from the drafting placeholder to the"
    echo "# permanent base, so the queries on the page match the data served."
    echo "title: $title"
    echo "slug: $slug"
    echo "description: >-"
    echo "  $desc"
    echo "---"
    echo
    sed -e "s|${OLD}|${NEW}|g" -e "s|](../CHANGELOG.md)|](${GH_BLOB}/CHANGELOG.md)|g" "$src"
  } > "$out"
  printf 'generated %-30s -> content/pages/%s  (/%s/)\n' "$1" "$2" "$slug"
}

stage_doc "docs/QUERIES.md" "record-harm-queries.md" "record-harm/queries" "Querying record harm" "SPARQL queries against the Record Harm Ontology: harm dependencies, aspect coverage, event and pattern analysis, and where a record lives."

stage_doc "docs/ONTOLOGY-COMPARISON.md" "record-harm-comparison.md" "record-harm/comparison" "Record harm compared" "How the Record Harm Ontology maps to STRIDE, the CIA triad, InterPARES diplomatics and spoliation doctrine, and what it deliberately does not cover."

# The generated pages must carry no placeholder IRI. Checked here, at the point
# of generation, rather than in build.py: example.org appears in legitimate
# prose elsewhere on the site (the "born at a permanent address" post is about
# the placeholder, and the migration note quotes it), so a build-wide HTML guard
# would fail on correct content. Here, zero is the right expectation.
for f in "$PAGES/record-harm-queries.md" "$PAGES/record-harm-comparison.md"; do
  [ -f "$f" ] || continue
  if grep -qE "https?://[^ <>]*example[.]org" "$f"; then
    echo "error: a placeholder IRI survived into $(basename "$f")" >&2
    exit 1
  fi
done

# Sanity: no example.org reference of any kind should remain in the hosted
# copies -- not even in a comment, since build.py --check greps the published
# output for the string and will fail the build if one survives.
if grep -rl "example.org" "$DEST" >/dev/null 2>&1; then
  echo "error: example.org still present in migrated output" >&2
  exit 1
fi
# And the rewritten TODO must not survive: it would claim the permanent base is
# a placeholder.
if grep -rl "RFC 2606 placeholder" "$DEST" >/dev/null 2>&1; then
  echo "error: the placeholder TODO survived into the hosted copy" >&2
  exit 1
fi
echo "done — hosted namespace is now ${NEW}"
